#!/bin/sh
#
# SPDX-License-Identifier: MIT
#

# Skip if no packages registered this intercept
grep -q "^##""PKGS:" "$0" || exit 0

set -e

[ -x "$D${libexecdir}/${binprefix}fc-cache" ] || exit 0

rm -f $D${fontconfigcachedir}/CACHEDIR.TAG

PSEUDO_UNLOAD=1 ${binprefix}qemuwrapper -L $D -E ${fontconfigcacheenv} $D${libexecdir}/${binprefix}fc-cache --sysroot=$D --system-only ${fontconfigcacheparams}

chown -R root:root $D${fontconfigcachedir}
find $D -type f -name .uuid -exec chown root:root '{}' +
