#!/bin/sh
#
# SPDX-License-Identifier: MIT
#
# Post-install intercept for mime-xdg.bbclass

# Skip if no packages registered this intercept
grep -q "^##""PKGS:" "$0" || exit 0

command -v update-desktop-database >/dev/null 2>&1 || exit 0
[ -d "$D${desktop_dir}" ] || exit 0
update-desktop-database $D${desktop_dir}
