#!/bin/sh
#
# SPDX-License-Identifier: MIT
#

# Skip if no packages registered this intercept
grep -q "^##""PKGS:" "$0" || exit 0

set -e

[ -x "$D${libdir}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" ] || exit 0

export GDK_PIXBUF_MODULEDIR=$D${libdir}/gdk-pixbuf-2.0/2.10.0/loaders
export GDK_PIXBUF_FATAL_LOADER=1

PSEUDO_UNLOAD=1 ${binprefix}qemuwrapper -L $D $D${libdir}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders \
    >$GDK_PIXBUF_MODULEDIR/../loaders.cache && \
    sed -i -e "s:$D::g" $GDK_PIXBUF_MODULEDIR/../loaders.cache
